### ISSUE TITLE
Error parsing config

### ISSUE THREAD

**Issue by SamPhoenix91** [kloknibor/motioneye-to-mqtt#1]
After configuring and running the file, it gives me the following error

Traceback (most recent call last):
  File "configparser.py", line 1138, in _unify_values
KeyError: 'MQTT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python_test4.py", line 15, in <module>
  File "configparser.py", line 781, in get
  File "configparser.py", line 1141, in _unify_values
configparser.NoSectionError: No section: 'MQTT'
[21538] Failed to execute script python_test4

**Comment by kloknibor** [comment]
This package unfortunately is no longer used by me and so not really maintained anymore....
